ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS consent_laser BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS consent_pmu   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS consent_at    TIMESTAMP;
